apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravaer
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://tjenester-q1.nav.no/sykefravaer"
    - "https://sykefravaer.nais.oera-q.local"
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: APPRES_CMS_URL
      value: https://appres-q1.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice-q.nav.no/login
    - name: SYFOAPI_SYFOMOTEADMINAPI_URL
      value: https://syfoapi.nais.oera-q.local/syfomoteadmin/api
    - name: SYFOAPI_SYFOTEKSTERAPI_URL
      value: https://syfoapi.nais.oera-q.local/syfotekster/api/tekster
    - name: SYFOSOKNAD_PROXY_URL
      value: https://syfosoknad-proxy.dev.nav.no
    - name: SYKEFRAVAERAPI_URL
      value: https://tjenester-q1.nav.no/syforest
    - name: OPPFOELGINGSDIALOGAPI_URL
      value: https://restoppfoelgingsdialog-q1.nais.oera-q.local/restoppfoelgingsdialog/api
    - name: SYFOUNLEASHAPI_URL
      value: https://syfounleash.nais.oera-q.local
    - name: DECORATOR_URL
      value: https://www-q1.nav.no/dekoratoren
