apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravaer
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - "https://tjenester-q1.nav.no/sykefravaer"
    - "https://sykefravaer.nais.oera-q.local"
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    - name: DECORATOR_URL
      value: https://www-q1.nav.no/dekoratoren
