const landliste = [
    'Afghanistan',
    'Albania',
    'Algerie',
    'Andorra',
    'Angola',
    'Antigua og Barbuda',
    'Argentina',
    'Armenia',
    'Aserbajdsjan',
    'Australia',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belgia',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia-Hercegovina',
    'Botswana',
    'Brasil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Canada',
    'Chile',
    'Colombia',
    'Cookøyene',
    'Costa Rica',
    'Cuba',
    'Danmark',
    'De forente arabiske emirater',
    'Den demokratiske republikken Kongo',
    'Den dominikanske republikk',
    'Den sentralafrikanske republikk',
    'Djibouti',
    'Dominica',
    'Ecuador',
    'Egypt',
    'Ekvatorial-Guinea',
    'El Salvador',
    'Elfenbenskysten',
    'Eritrea',
    'Estland',
    'Etiopia',
    'Fiji',
    'Filippinene',
    'Finland',
    'Folkerepublikken Kina',
    'Frankrike',
    'Gabon',
    'Gambia',
    'Georgia',
    'Ghana',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Hellas',
    'Honduras',
    'Hviterussland',
    'India',
    'Indonesia',
    'Irak',
    'Iran',
    'Irland',
    'Island',
    'Israel',
    'Italia',
    'Jamaica',
    'Japan',
    'Jemen',
    'Jordan',
    'Kambodsja',
    'Kamerun',
    'Kapp Verde',
    'Kasakhstan',
    'Kenya',
    'Kirgisistan',
    'Kiribati',
    'Komorene',
    'Kosovo',
    'Kroatia',
    'Kuwait',
    'Laos',
    'Latvia',
    'Lesotho',
    'Libanon',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Litauen',
    'Luxembourg',
    'Madagaskar',
    'Makedonia',
    'Malawi',
    'Malaysia',
    'Maldivene',
    'Mali',
    'Malta',
    'Marokko',
    'Marshalløyene',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Mikronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Mosambik',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nederland',
    'Nepal',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Nord-Korea',
    'Norge',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua Ny-Guinea',
    'Paraguay',
    'Peru',
    'Polen',
    'Portugal',
    'Qatar',
    'Republikken Kina',
    'Republikken Kongo',
    'Republikken Kypros',
    'Romania',
    'Russland',
    'Rwanda',
    'Saint Kitts og Nevis',
    'Saint Lucia',
    'Saint Vincent og Grenadinene',
    'Salomonøyene',
    'Samoa',
    'San Marino',
    'São Tomé og Príncipe',
    'Saudi-Arabia',
    'Senegal',
    'Serbia',
    'Seychellene',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'Spania',
    'Sri Lanka',
    'Storbritannia',
    'Sudan',
    'Surinam',
    'Sveits',
    'Sverige',
    'Swaziland',
    'Syria',
    'Sør-Afrika',
    'Sør-Korea',
    'Sør-Sudan',
    'Tadsjikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad og Tobago',
    'Tsjad',
    'Tsjekkia',
    'Tunisia',
    'Turkmenistan',
    'Tuvalu',
    'Tyrkia',
    'Tyskland',
    'Uganda',
    'Ukraina',
    'Ungarn',
    'Uruguay',
    'USA',
    'Usbekistan',
    'Vanuatu',
    'Vatikanstaten',
    'Venezuela',
    'Vest-Sahara',
    'Vietnam',
    'Zambia',
    'Zimbabwe',
    'Øst-Timor',
    'Østerrike',
];

export default landliste;
