const soknad1 = {
    id: '6ae67ec4-1df1-4746-85e4-2d4ee1c0e144',
    sykmeldingId: 'd2a3419d-69cc-4f60-a391-e87eb18cec29',
    soknadstype: 'SELVSTENDIGE_OG_FRILANSERE',
    status: 'NY',
    fom: '2018-03-17',
    tom: '2018-03-26',
    opprettetDato: '2018-05-28',
    sporsmal: [
        {
            id: '1',
            tag: 'ANSVARSERKLARING',
            sporsmalstekst: 'Jeg vet at dersom jeg gir uriktige opplysninger...',
            svar: {
                svartype: 'CHECKBOX',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: null,
                undersporsmal: [],
            },
        },
        {
            id: '2',
            tag: 'TILBAKE_I_ARBEID',
            sporsmalstekst: 'Var du tilbake i fullt arbeid som selvstendig næringsdrivende før sykmeldingsperioden utløp 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '3',
                        tag: 'TILBAKE_NAR',
                        sporsmalstekst: 'Når var du tilbake i arbeid?',
                        svar: {
                            svartype: 'DATO',
                            svarverdi: [],
                            min: '2018-03-17',
                            max: '2018-03-26',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '4',
            tag: 'JOBBET_DU_GRADERT_0',
            sporsmalstekst: 'I perioden 17.03.2018 - 22.03.2018 skulle du ifølge sykmeldingen jobbe 20% som selvstendig næringsdrivende. Jobbet du mer enn dette?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '5',
                        tag: 'HVOR_MANGE_TIMER_0',
                        sporsmalstekst: 'Hvor mange timer jobbet du normalt per uke som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'TIMER',
                            svarverdi: [],
                            min: '1',
                            max: '150',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '6',
                        tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                        sporsmalstekst: 'Hvor mye jobbet du totalt i denne perioden som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'PROSENT',
                            svarverdi: [],
                            min: '21',
                            max: '100',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '7',
            tag: 'JOBBET_DU_GRADERT_1',
            sporsmalstekst: 'I perioden 23.03.2018 - 26.03.2018 skulle du ifølge sykmeldingen jobbe 40% som selvstendig næringsdrivende. Jobbet du mer enn dette?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '8',
                        tag: 'HVOR_MANGE_TIMER_1',
                        sporsmalstekst: 'Hvor mange timer jobbet du normalt per uke som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'TIMER',
                            svarverdi: [],
                            min: '1',
                            max: '150',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '9',
                        tag: 'HVOR_MYE_HAR_DU_JOBBET_1',
                        sporsmalstekst: 'Hvor mye jobbet du totalt i denne perioden som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'PROSENT',
                            svarverdi: [],
                            min: '1',
                            max: '40',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '10',
            tag: 'ANDRE_INNTEKTSKILDER',
            sporsmalstekst: 'Har du andre inntektskilder eller arbeidsforhold?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '11',
                        tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                        sporsmalstekst: 'Hvilke andre inntektskilder har du?',
                        svar: {
                            svartype: 'CHECKBOX_GRUPPE',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [
                                {
                                    id: '12',
                                    tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD',
                                    sporsmalstekst: 'Arbeidsforhold',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '13',
                                                tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '14',
                                    tag: 'INNTEKTSKILDE_JORDBRUKER',
                                    sporsmalstekst: 'Jordbruker / Fisker / Reindriftsutøver',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '15',
                                                tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '16',
                                    tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG',
                                    sporsmalstekst: 'Frilanser',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '17',
                                                tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '18',
                                    tag: 'INNTEKTSKILDE_ANNET',
                                    sporsmalstekst: 'Annet',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            id: '20',
            tag: 'UTLAND',
            sporsmalstekst: 'Har du oppholdt deg i utlandet i perioden 17.03.2018 - 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '21',
                        tag: 'PERIODER',
                        sporsmalstekst: null,
                        svar: {
                            svartype: 'PERIODER',
                            svarverdi: [],
                            min: '2018-03-17',
                            max: '2018-03-26',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '22',
                        tag: 'UTLANDSOPPHOLD_SOKT_SYKEPENGER',
                        sporsmalstekst: 'Har du søkt om å beholde sykepenger under dette oppholdet utenfor Norge?',
                        svar: {
                            svartype: 'JA_NEI',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '23',
            tag: 'UTDANNING',
            sporsmalstekst: 'Har du vært under utdanning i løpet av perioden 17.03.2018 - 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '24',
                        tag: 'UTDANNING_START',
                        sporsmalstekst: 'Når startet du på utdanningen?',
                        svar: {
                            svartype: 'DATO',
                            svarverdi: [],
                            min: null,
                            max: '2018-03-26',
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '25',
                        tag: 'FULLTIDSSTUDIUM',
                        sporsmalstekst: 'Er utdanningen et fulltidsstudium?',
                        svar: {
                            svartype: 'JA_NEI',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '49',
            tag: 'BEKREFT_OPPLYSNINGER',
            sporsmalstekst: 'Jeg har lest all informasjonen jeg har fått i søknaden og bekrefter at opplysningene jeg har gitt er korrekte.',
            undertekst: null,
            svar: {
                svartype: 'CHECKBOX',
                svarverdi: [
                    {
                        svarverdiType: null,
                        verdi: 'CHECKED',
                    },
                ],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: null,
                undersporsmal: [],
            },
        },
    ],
};

const parsetSoknad1 = {
    id: '6ae67ec4-1df1-4746-85e4-2d4ee1c0e144',
    sykmeldingId: 'd2a3419d-69cc-4f60-a391-e87eb18cec29',
    soknadstype: 'SELVSTENDIGE_OG_FRILANSERE',
    status: 'NY',
    fom: new Date('2018-03-17'),
    tom: new Date('2018-03-26'),
    opprettetDato: new Date('2018-05-28'),
    sporsmal: [
        {
            id: '1',
            tag: 'ANSVARSERKLARING',
            sporsmalstekst: 'Jeg vet at dersom jeg gir uriktige opplysninger...',
            svar: {
                svartype: 'CHECKBOX',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: null,
                undersporsmal: [],
            },
        },
        {
            id: '2',
            tag: 'TILBAKE_I_ARBEID',
            sporsmalstekst: 'Var du tilbake i fullt arbeid som selvstendig næringsdrivende før sykmeldingsperioden utløp 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '3',
                        tag: 'TILBAKE_NAR',
                        sporsmalstekst: 'Når var du tilbake i arbeid?',
                        svar: {
                            svartype: 'DATO',
                            svarverdi: [],
                            min: new Date('2018-03-17'),
                            max: new Date('2018-03-26'),
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '4',
            tag: 'JOBBET_DU_GRADERT_0',
            sporsmalstekst: 'I perioden 17.03.2018 - 22.03.2018 skulle du ifølge sykmeldingen jobbe 20% som selvstendig næringsdrivende. Jobbet du mer enn dette?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '5',
                        tag: 'HVOR_MANGE_TIMER_0',
                        sporsmalstekst: 'Hvor mange timer jobbet du normalt per uke som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'TIMER',
                            svarverdi: [],
                            min: 1,
                            max: 150,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '6',
                        tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                        sporsmalstekst: 'Hvor mye jobbet du totalt i denne perioden som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'PROSENT',
                            svarverdi: [],
                            min: 21,
                            max: 100,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '7',
            tag: 'JOBBET_DU_GRADERT_1',
            sporsmalstekst: 'I perioden 23.03.2018 - 26.03.2018 skulle du ifølge sykmeldingen jobbe 40% som selvstendig næringsdrivende. Jobbet du mer enn dette?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '8',
                        tag: 'HVOR_MANGE_TIMER_1',
                        sporsmalstekst: 'Hvor mange timer jobbet du normalt per uke som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'TIMER',
                            svarverdi: [],
                            min: 1,
                            max: 150,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '9',
                        tag: 'HVOR_MYE_HAR_DU_JOBBET_1',
                        sporsmalstekst: 'Hvor mye jobbet du totalt i denne perioden som selvstendig næringsdrivende?',
                        svar: {
                            svartype: 'PROSENT',
                            svarverdi: [],
                            min: 1,
                            max: 40,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '10',
            tag: 'ANDRE_INNTEKTSKILDER',
            sporsmalstekst: 'Har du andre inntektskilder eller arbeidsforhold?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '11',
                        tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                        sporsmalstekst: 'Hvilke andre inntektskilder har du?',
                        svar: {
                            svartype: 'CHECKBOX_GRUPPE',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [
                                {
                                    id: '12',
                                    tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD',
                                    sporsmalstekst: 'Arbeidsforhold',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '13',
                                                tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '14',
                                    tag: 'INNTEKTSKILDE_JORDBRUKER',
                                    sporsmalstekst: 'Jordbruker / Fisker / Reindriftsutøver',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '15',
                                                tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '16',
                                    tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG',
                                    sporsmalstekst: 'Frilanser',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [
                                            {
                                                id: '17',
                                                tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT',
                                                sporsmalstekst: 'Er du sykmeldt fra dette?',
                                                svar: {
                                                    svartype: 'JA_NEI',
                                                    svarverdi: [],
                                                    min: null,
                                                    max: null,
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    undersporsmal: [],
                                                },
                                            },
                                        ],
                                    },
                                },
                                {
                                    id: '18',
                                    tag: 'INNTEKTSKILDE_ANNET',
                                    sporsmalstekst: 'Annet',
                                    svar: {
                                        svartype: 'CHECKBOX',
                                        svarverdi: [],
                                        min: null,
                                        max: null,
                                        kriterieForVisningAvUndersporsmal: 'CHECKED',
                                        undersporsmal: [],
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
        {
            id: '20',
            tag: 'UTLAND',
            sporsmalstekst: 'Har du oppholdt deg i utlandet i perioden 17.03.2018 - 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '21',
                        tag: 'PERIODER',
                        sporsmalstekst: null,
                        svar: {
                            svartype: 'PERIODER',
                            svarverdi: [],
                            min: new Date('2018-03-17'),
                            max: new Date('2018-03-26'),
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '22',
                        tag: 'UTLANDSOPPHOLD_SOKT_SYKEPENGER',
                        sporsmalstekst: 'Har du søkt om å beholde sykepenger under dette oppholdet utenfor Norge?',
                        svar: {
                            svartype: 'JA_NEI',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '23',
            tag: 'UTDANNING',
            sporsmalstekst: 'Har du vært under utdanning i løpet av perioden 17.03.2018 - 26.03.2018?',
            svar: {
                svartype: 'JA_NEI',
                svarverdi: [],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: 'JA',
                undersporsmal: [
                    {
                        id: '24',
                        tag: 'UTDANNING_START',
                        sporsmalstekst: 'Når startet du på utdanningen?',
                        svar: {
                            svartype: 'DATO',
                            svarverdi: [],
                            min: null,
                            max: new Date('2018-03-26'),
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                    {
                        id: '25',
                        tag: 'FULLTIDSSTUDIUM',
                        sporsmalstekst: 'Er utdanningen et fulltidsstudium?',
                        svar: {
                            svartype: 'JA_NEI',
                            svarverdi: [],
                            min: null,
                            max: null,
                            kriterieForVisningAvUndersporsmal: null,
                            undersporsmal: [],
                        },
                    },
                ],
            },
        },
        {
            id: '49',
            tag: 'BEKREFT_OPPLYSNINGER',
            sporsmalstekst: 'Jeg har lest all informasjonen jeg har fått i søknaden og bekrefter at opplysningene jeg har gitt er korrekte.',
            undertekst: null,
            svar: {
                svartype: 'CHECKBOX',
                svarverdi: [
                    {
                        svarverdiType: null,
                        verdi: 'CHECKED',
                    },
                ],
                min: null,
                max: null,
                kriterieForVisningAvUndersporsmal: null,
                undersporsmal: [],
            },
        },
    ],
};

export const soknadrespons = [soknad1];

export const getSoknad = (soknad = {}) => {
    return {
        ...parsetSoknad1,
        ...soknad,
    };
};

export default [parsetSoknad1];
