export const ANDRE_ARBEIDSFORHOLD = 'ANDRE_ARBEIDSFORHOLD';
export const SELVSTENDIG_NAERINGSDRIVENDE = 'SELVSTENDIG_NAERINGSDRIVENDE';
export const SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA = 'SELVSTENDIG_NAERINGSDRIVENDE_DAGMAMMA';
export const JORDBRUKER_FISKER_REINDRIFTSUTOEVER = 'JORDBRUKER_FISKER_REINDRIFTSUTOEVER';
export const FRILANSER = 'FRILANSER';
export const ANNET = 'ANNET';
