const ledetekster = {
	"sykmelding.vis.periode.tittel":"Periode",
	"dine-sykmeldinger.tittel":"Dine sykmeldinger",
	"sykmelding.vis.friskmelding.tekst":"arbeidsfør etter perioden",
	"sykmelding.teaser.dato":"fra %FOM% til %TOM%",
	"dine-sykmeldinger.introduksjonstekst":"NAV mottar alle sykmeldinger fra leger og andre som kan sykmelde. På denne siden kan du se sykmeldingene dine. Når det gjelder sykepenger, må du fortsatt <a href=\"https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykepenger\">søke</a> om dette på vanlig måte.",
	"sykmelding.vis.avsender.tittel":"Avsender",
	"sykmelding.vis.flere-opplysninger.tittel":"Flere opplysninger fra lege",
	"sykmelding.vis.diagnose.tittel":"Diagnose",
	"404.tekst":"Fant ikke siden du lette etter  er du sikker på at du er på riktig sted?",
	"sykmelding.send-til-arbeidsgiver.avbryt":"Avbryt",
	"sykmelding.vis.sidetittel":"Din sykmelding",
	"sykmelding.vis.friskmelding.tittel":"Friskmelding",
	"sykmelding.send-til-arbeidsgiver.sok-etter-arbeidsgiver.label":"Er det ikke en av disse? Søk etter arbeidsgiver.",
	"sykmelding.send-til-arbeidsgiver.sok-etter-arbeidsgiver.placeholder":"Søk",
	"dine-sykmeldinger.informasjon.tittel":"Hvem gjør hva når du er sykmeldt",
	"sykmelding.send-til-arbeidsgiver.tittel":"Send sykmelding til arbeidsgiver",
	"applikasjon.siden-laster":"Siden laster",
	"sykmelding.send-til-arbeidsgiver.velg-arbeidsgiver.sporsmal":"Arbeidsgiver for denne sykmeldingen",
	"sykmelding.send-til-arbeidsgiver.kvittering.tittel":"Sykmeldingen er sendt til arbeidsgiver",
	"sykmelding.vis.grad.tekst":"%GRAD% % sykmeldt",
	"dine-sykmeldinger.aktive-sykmeldinger.tittel":"Aktive sykmeldinger",
	"sykmelding.vis.avvis.tekst":"Avvis sykmelding",
	"dine-sykmeldinger.sidetittel":"Dine sykmeldinger",
	"sykmelding.send-til-arbeidsgiver.infotekst":"En forklarende tekst",
	"404.tittel":"Ooops!",
	"dine-sykmeldinger.informasjon.tekst":"<p>Du kan bli sykmeldt når det er medisinske grunner som hindrer deg i å være i arbeid. Ofte er det likevel mulig å være helt eller delvis i arbeid hvis arbeidsgiveren kan gjøre tilpasninger for deg på arbeidsplassen.</p><h3>Sykmeldt</h3><p>Som sykmeldt skal du være med og finne løsninger slik at sykefraværet ditt ikke varer lenger enn nødvendig. </p><h3>Lege/sykmelder</h3><p>Den som sykmelder deg skal vurdere om det er nødvendig med hel eller delvis sykmelding og anbefale aktivitet hvis det er medisinsk forsvarlig.</p><h3>Arbeidsgiver</h3><p>Arbeidsgiveren skal følge deg opp og legge til rette for at du kan være i aktivitet på arbeidsplassen. </p><h3>NAV</h3><p>Hvis du ikke har tilknytning til en arbeidsgiver, er det NAV-kontoret som skal gi deg veiledning og oppfølging. NAV har også ansvaret for å utbetale sykepenger, enten til deg eller til arbeidsgiveren.</p>",
	"sykmelding.vis.bekreft.tekst":"Gå videre",
	"sykmelding.vis.periode.tekst":"Fra og med <strong>%FOM%</strong> til og med <strong>%TOM%</strong>  %DAGER% dager",
	"sykmelding.teaser.fulltittel":"Sykmelding fra %FOM% til %TOM%",
	"sykmelding.teaser.tekst":"Du er %GRAD% % sykmeldt fra %ARBEIDSGIVER% i %DAGER% dager",
	"sykmelding.vis.tittel":"Sykmelding",
	"sykmelding.teaser.tittel":"Sykmelding",
	"sykmelding.vis.hovedtittel":"Din sykmelding",
	"sykmelding.vis.arbeidsgiver.tittel":"Arbeidsgiver for denne sykmeldingen",
	"sykmelding.vis.grad.tittel":"Grad",
	"dine-sykmeldinger.tidligere-sykmeldinger.tittel":"Tidligere sykmeldinger",
	"sykmelding.send-til-arbeidsgiver.send":"Send til arbeidsgiver"
};

export default ledetekster; 