const ledetekster = {
	"404.tittel":"Ooops!",
	"404.tekst":"Fant ikke siden du lette etter. Er du sikker på at du er på riktig sted?",
	"dine-sykmeldinger.sidetittel":"Dine sykmeldinger",
	"dine-sykmeldinger.tittel":"Dine sykmeldinger",
	"dine-sykmeldinger.introduksjonstekst":"NAV mottar sykmeldinger fra leger og andre som kan sykmelde. På denne siden kan du se sykmeldingene dine. Du kan foreløpig ikke søke om sykepenger digitalt. <a href='https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykepenger>Les mer om sykepenger her.</a>",
	"dine-sykmeldinger.aktive-sykmeldinger.tittel":"Aktive sykmeldinger",
	"dine-sykmeldinger.tidligere-sykmeldinger.tittel":"Tidligere sykmeldinger",
	"dine-sykmeldinger.ingen-sykmeldinger.melding":"Du har ingen sykmeldinger",
	"sykmelding.teaser.fulltittel":"Sykmelding fra %FOM% til %TOM%",
	"sykmelding.teaser.tittel":"Sykmelding",
	"sykmelding.teaser.dato":"fra %FOM% til %TOM%",
	"sykmelding.teaser.tekst":"Du er %GRAD% % sykmeldt fra %ARBEIDSGIVER% i %DAGER% dager",
	"sykmelding.teaser.tekst.ingen-grad":"Du er sykmeldt fra %ARBEIDSGIVER% i %DAGER% dager",
	"sykmelding.teaser.tekst.uten-arbeidsgiver":"Du er %GRAD% % sykmeldt i %DAGER% dager",
	"sykmelding.teaser.tekst.en-dag":"Du er %GRAD% % sykmeldt fra %ARBEIDSGIVER% i %DAGER% dag",
	"sykmelding.teaser.tekst.en-dag.ingen-grad":"Du er sykmeldt fra %ARBEIDSGIVER% i %DAGER% dag",
	"sykmelding.teaser.tekst.uten-arbeidsgiver.ingen-grad":"Du er sykmeldt i %DAGER% dager",
	"sykmelding.teaser.tekst.en-dag.uten-arbeidsgiver.ingen-grad":"Du er sykmeldt i %DAGER% dag",
	"sykmelding.teaser.tekst.en-dag.uten-arbeidsgiver":"Du er %GRAD% % sykmeldt i %DAGER% dag",
	"sykmelding.teaser.tekst.behandlingsdager":"Du har %BEHANDLINGSDAGER% behandlingsdager i løpet av %DAGER% dager – %ARBEIDSGIVER%",
	"sykmelding.teaser.tekst.behandlingsdager.uten-arbeidsgiver":"Du har %BEHANDLINGSDAGER% behandlingsdager i løpet av %DAGER% dager",
	"sykmelding.teaser.tekst.behandlingsdag":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dager – %ARBEIDSGIVER%",
	"sykmelding.teaser.tekst.behandlingsdag.en-dag.uten-arbeidsgiver.ingen-grad":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dag",
	"sykmelding.teaser.tekst.behandlingsdager.uten-arbeidsgiver.ingen-grad":"Du har %BEHANDLINGSDAGER% behandlingsdager i løpet av %DAGER% dager",
	"sykmelding.teaser.tekst.behandlingsdag.en-dag":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dag – %ARBEIDSGIVER%",
	"sykmelding.teaser.tekst.behandlingsdag.en-dag.uten-arbeidsgiver":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dag",
	"sykmelding.teaser.tekst.behandlingsdager.en-dag.uten-arbeidsgiver.ingen-grad":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dag",
	"sykmelding.teaser.tekst.behandlingsdag.uten-arbeidsgiver":"Du har %BEHANDLINGSDAGER% behandlingsdag i løpet av %DAGER% dager",
	"sykmelding.teaser.tekst.reisetilskudd":"Du har reisetilskudd i %DAGER% dager",
	"sykmelding.teaser.tekst.reisetilskudd.en-dag":"Du har reisetilskudd i %DAGER% dag",
	"sykmelding.teaser.tekst.reisetilskudd.en-dag.uten-arbeidsgiver":"Du har reisetilskudd i %DAGER% dag",
	"sykmelding.teaser.tekst.reisetilskudd.en-dag.uten-arbeidsgiver.ingen-grad":"Du har reisetilskudd i %DAGER% dag",
	"sykmelding.teaser.tekst.avventende":"Du er avventende sykmeldt fra %ARBEIDSGIVER% i %DAGER% dager",
	"sykmelding.teaser.tekst.avventende.uten-arbeidsgiver":"Du er avventende sykmeldt i %DAGER% dager",
	"sykmelding.teaser.tekst.avventende.en-dag":"Du er avventende sykmeldt fra %ARBEIDSGIVER% i %DAGER% dag",
	"sykmelding.teaser.tekst.avventende.ingen-grad":"Du er avventende sykmeldt fra %ARBEIDSGIVER% i %DAGER% dager",
	"sykmelding.teaser.tekst.avventende.en-dag.uten-arbeidsgiver":"Du er avventende sykmeldt i %DAGER% dag",
	"sykmelding.teaser.tekst.avventende.en-dag.uten-arbeidsgiver.ingen-grad":"Du er avventende sykmeldt i %DAGER% dag",
	"sykmelding.vis.sidetittel":"Din sykmelding",
	"sykmelding.vis.hovedtittel":"Din sykmelding",
	"sykmelding.vis.tittel":"Sykmelding",
	"sykmelding.vis.periode.tittel":"Periode",
	"sykmelding.vis.periode.dag":"dag",
	"sykmelding.vis.periode.dager":"dager",
	"sykmelding.vis.periode.med.reisetilskudd":"med reisetilskudd",
	"sykmelding.vis.periode.behandlingsdager":"behandlingsdager",
	"sykmelding.vis.periode.reisetilskudd.tittel":"Reisetilskudd",
	"sykmelding.vis.periode.avventende":"Avventende sykmelding",
	"sykmelding.vis.periode.avventende.innspill":"Innspill til arbeidsgiver om tilrettelegging",
	"sykmelding.vis.periode.tekst":"Fra og med <strong>%FOM%</strong> til og med <strong>%TOM%</strong> – %DAGER% dager",
	"sykmelding.vis.grad.tittel":"Grad",
	"sykmelding.vis.grad.tekst":"%GRAD% % sykmeldt",
	"sykmelding.vis.arbeidsgiver.tittel":"Arbeidsgiver for denne sykmeldingen",
	"sykmelding.vis.avsender.tittel":"Lege / sykmelder",
	"sykmelding.vis.diagnose.tittel":"Diagnose",
	"sykmelding.vis.diagnosekode.tittel":"Diagnosekode",
	"sykmelding.vis.diagnosesystem.tittel":"Diagnosesystem",
	"sykmelding.vis.bidiagnose.tittel":"Bidiagnose",
	"sykmelding.vis.svangerskap.tittel":"Sykdommen er svangerskapsrelatert",
	"sykmelding.vis.yrkesskade.tittel":"Sykdommen kan skyldes en skade/yrkessykdom",
	"sykmelding.vis.arbeidsfoer.tittel":"Pasienten er 100 % arbeidsfør etter perioden",
	"sykmelding.vis.hensyn.tittel":"Beskriv eventuelle hensyn som må tas på arbeidsplassen",
	"sykmelding.vis.flere-opplysninger.tittel":"Flere opplysninger fra den som har sykmeldt deg",
	"sykmelding.vis.arbeidsevne.tittel":"Hva skal til for å bedre arbeidsevnen?",
	"sykmelding.vis.arbeidsevne.tilrettelegging":"Tilrettelegging/hensyn som bør tas på arbeidsplassen",
	"sykmelding.vis.arbeidsevne.tiltaknav":"Tiltak i regi av/innspill til NAV",
	"sykmelding.vis.arbeidsevne.tiltakandre":"Eventuelle andre tiltak/innspill",
	"sykmelding.vis.friskmelding.tittel":"Friskmelding",
	"sykmelding.vis.friskmelding.retur.samme.arbeidsgiver.tittel":"Jeg antar at pasienten på sikt kan komme tilbake til eget eller annet arbeid hos samme arbeidsgiver",
	"sykmelding.vis.friskmelding.retur.samme.arbeidsgiver.dato":"Når antar du at det kan skje?",
	"sykmelding.vis.friskmelding.retur.annen.arbeidsgiver.tittel":"Jeg antar at pasienten på sikt kan komme tilbake til eget eller annet arbeid hos annen arbeidsgiver",
	"sykmelding.vis.friskmelding.retur.usikker.tittel":"Jeg er usikker på om pasienten kan komme tilbake i arbeid hos egen eller annen arbeidsgiver",
	"sykmelding.vis.friskmelding.retur.usikker.dato":"Når antar du å kunne gi tilbakemelding på dette?",
	"sykmelding.vis.friskmelding.uten.arbeidsgiver.retur.tittel":"Jeg antar at pasienten på sikt kan komme tilbake i arbeid",
	"sykmelding.vis.friskmelding.uten.arbeidsgiver.retur.dato":"Når antar du at dette kan skje?",
	"sykmelding.vis.friskmelding.uten.arbeidsgiver.usikker.tittel":"Jeg er usikker på om pasienten kan komme tilbake i arbeid",
	"sykmelding.vis.friskmelding.uten.arbeidsgiver.usikker.dato":"Når antar du å kunne gi tilbakemelding på dette?",
	"sykmelding.vis.meldingarbeidsgiver.tittel":"Melding til arbeidsgiver",
	"sykmelding.vis.meldingarbeidsgiver.innspill.tittel":"Innspill til arbeidsgiver",
	"sykmelding.vis.meldingnav.tittel":"Melding til NAV",
	"sykmelding.vis.meldingnav.navboertatakisaken.tittel":"NAV bør ta tak i saken nå",
	"sykmelding.vis.meldingnav.navboertatakisaken.begrunnelse.tittel":"Begrunn hvorfor",
	"sykmelding.vis.mulighet.for.arbeid.tittel":"Mulighet for arbeid",
	"sykmelding.vis.mulighet.for.arbeid.start.legemeldt.fravaer.tittel":"Når startet det legemeldte fraværet?",
	"sykmelding.vis.mulighet.for.arbeid.pasient.ikke.i.arbeid.tittel":"Pasienten kan ikke være i arbeid (100 % sykmeldt)",
	"sykmelding.vis.mulighet.for.arbeid.medisinsk.tittel":"Det er medisinske årsaker som hindrer arbeidsrelatert aktivitet",
	"sykmelding.vis.mulighet.for.arbeid.medisinsk.beskriv.tittel":"Beskriv årsaken til at arbeidsrelatert aktivitet ikke er mulig",
	"sykmelding.vis.mulighet.for.arbeid.forhold.arbeidsplassen.tittel":"Det er forhold på arbeidsplassen som hindrer arbeidsrelatert aktivitet",
	"sykmelding.vis.mulighet.for.arbeid.forhold.arbeidsplassen.beskriv.tittel":"Beskriv årsaken til at arbeidsrelatert aktivitet ikke er mulig",
	"sykmelding.vis.tilbakedatering.tittel":"Tilbakedatering",
	"sykmelding.vis.tilbakedatering.kontakt.dato":"Oppgi dato for dokumenterbar kontakt med pasienten",
	"sykmelding.vis.tilbakedatering.begrunnelse":"Begrunnelse for tilbakedatering",
	"sykmelding.vis.annet.tittel":"Annet",
	"sykmelding.vis.annet.telefon":"Telefon til lege/sykmelder",
	"sykmelding.vis.annet.utstedelsesdato":"Dato sykmeldingen ble skrevet",
	"sykmelding.vis.utdypende.tittel":"Utdypende opplysninger",
	"sykmelding.vis.utdypende.sykehistorie.tittel":"Beskriv kort sykehistorie, symptomer og funn i dagens situasjon",
	"sykmelding.vis.utdypende.paavirkning.arbeidsevne.tittel":"Hvordan påvirker sykdommen arbeidsevnen?",
	"sykmelding.vis.utdypende.behandlingsresultat.tittel":"Har behandlingen frem til nå bedret arbeidsevnen?",
	"sykmelding.vis.utdypende.henvisning.tittel":"Beskriv pågående og planlagt henvisning, utredning og/eller behandling",
	"sykmelding.vis.bekreft.tekst":"Gå videre",
	"sykmelding.vis.avvis.tekst":"Avvis sykmelding",
	"sykmelding.vis.tilbake":"Tilbake til dine sykmeldinger",
	"sykmelding.vis.fant-ikke-sykmelding.tittel":"Vi finner ikke denne sykmeldingen!",
	"sykmelding.vis.fant-ikke-sykmelding.melding":"Vi finner dessverre ikke sykmeldingen du ser etter.",
	"sykmelding.send-til-arbeidsgiver.tittel":"Send sykmelding til arbeidsgiver",
	"sykmelding.send-til-arbeidsgiver.infotekst":"En forklarende tekst",
	"sykmelding.send-til-arbeidsgiver.velg-arbeidsgiver.sporsmal":"Arbeidsgiver for denne sykmeldingen",
	"sykmelding.send-til-arbeidsgiver.sok-etter-arbeidsgiver.label":"Er det ikke en av disse? Søk etter arbeidsgiver.",
	"sykmelding.send-til-arbeidsgiver.sok-etter-arbeidsgiver.placeholder":"Søk",
	"sykmelding.send-til-arbeidsgiver.send":"Send til arbeidsgiver",
	"sykmelding.send-til-arbeidsgiver.avbryt":"Avbryt",
	"sykmelding.send-til-arbeidsgiver.kvittering.tittel":"Sykmeldingen er sendt til arbeidsgiver",
	"landingsside.tilsykmeldinger.lenketekst": "Dine sykmeldinger",
	"landingsside.generell.informasjon.tekst": "Hvis du blir sykmeldt, trenger du å kjenne til hvilke regler som gjelder for oppfølging og for å få utbetalt sykepenger. <a target=\"blank\" href=\"https://www.nav.no/no/Person/Arbeid/Sykmeldt%2C+arbeidsavklaringspenger+og+yrkesskade/Sykmeldt\">Les mer om sykpenger og sykefraværsoppfølging</a>.</p>",
	"landingsside.sidetittel": "Ditt sykefravær",
	"landingsside.informasjon.tittel": "Hvem gjør hva når du er sykmeldt",
	"landingsside.informasjon.tekst": "<p>Du kan bli sykmeldt når det er medisinske grunner som hindrer deg i å være i arbeid. Ofte er det likevel mulig å være helt eller delvis i arbeid hvis arbeidsgiveren kan gjøre tilpasninger for deg på arbeidsplassen.</p><h3>Sykmeldt</h3><p>Som sykmeldt skal du være med og finne løsninger slik at sykefraværet ditt ikke varer lenger enn nødvendig. </p><h3>Lege/sykmelder</h3><p>Den som sykmelder deg skal vurdere om det er nødvendig med hel eller delvis sykmelding og anbefale aktivitet hvis det er medisinsk forsvarlig.</p><h3>Arbeidsgiver</h3><p>Arbeidsgiveren skal følge deg opp og legge til rette for at du kan være i aktivitet på arbeidsplassen. </p><h3>NAV</h3><p>Hvis du ikke har tilknytning til en arbeidsgiver, er det NAV-kontoret som skal gi deg veiledning og oppfølging.</p>",
	"under-utvikling.varsel.tekst":"Sidene er under kontinuerlig utvikling og vil på sikt inneholde mer tilpasset informasjon og flere verktøy. Løsningen inneholder en digital visning av sykmeldingen. Om du kan se sykmeldingen avhenger av hvilket system din lege/sykmelder bruker.",
	"under-utvikling.varsel.tittel":"Første versjon av ny tjeneste",
};

export default ledetekster; 