export const ARBEIDSTAKER = 'ARBEIDSTAKER';
export const NAERINGSDRIVENDE = 'NAERINGSDRIVENDE';
export const FRILANSER = 'FRILANSER';
export const ARBEIDSLEDIG = 'ARBEIDSLEDIG';
export const ANNET = 'ANNET';
export const DEFAULT = 'DEFAULT';
