export const AVVENTENDE_SYKMELDING = 'AVVENTENDE_SYKMELDING';
export const IKKE_DIGITALISERT = 'IKKE_DIGITALISERT';
export const SOKNAD_OPPRETTET = 'SOKNAD_OPPRETTET';
export const INNENFOR_VENTETID = 'INNENFOR_VENTETID';
export const IGNORERT = 'IGNORERT';

export const FERDIG_BEHANDLET_STATUSER = [AVVENTENDE_SYKMELDING, IKKE_DIGITALISERT, SOKNAD_OPPRETTET, INNENFOR_VENTETID, IGNORERT];
