export const sykmeldingskjemamodi = {
    AVBRYT: 'AVBRYT',
    SEND_MED_NAERMESTE_LEDER: 'SEND-MED-NAERMESTE-LEDER',
    SEND: 'SEND',
    BEKREFT: 'BEKREFT',
};

export const ANNEN_ARBEIDSGIVER_ORGNUMMER = '0';
export const ANNEN_ARBEIDSSITUASJON = 'ANNEN_ARBEIDSSITUASJON';
export const AKTIVITET_IKKE_MULIG = 'AKTIVITET_IKKE_MULIG';
export const AVVENTENDE = 'AVVENTENDE';
export const BEHANDLINGSDAGER = 'BEHANDLINGSDAGER';
export const GRADERT = 'GRADERT';
export const REISETILSKUDD = 'REISETILSKUDD';
