export const HENTER_ARBEIDSGIVERS_SYKMELDINGER = 'HENTER_ARBEIDSGIVERS_SYKMELDINGER';
export const HENT_ARBEIDSGIVERS_SYKMELDINGER_FEILET = 'HENT_ARBEIDSGIVERS_SYKMELDINGER_FEILET';
export const SET_ARBEIDSGIVERS_SYKMELDINGER = 'SET_ARBEIDSGIVERS_SYKMELDINGER';
export const HENT_ARBEIDSGIVERS_SYKMELDINGER_FORESPURT = 'HENT_ARBEIDSGIVERS_SYKMELDINGER_FORESPURT';

export const SKJUL_UNDER_UTVIKLING_VARSEL = 'SKJUL_UNDER_UTVIKLING_VARSEL';
export const HENT_BRUKERINFO_FEILET = 'HENT_BRUKERINFO_FEILET';
export const HENTER_BRUKERINFO = 'HENTER_BRUKERINFO';
export const SET_BRUKERINFO = 'SET_BRUKERINFO';
export const SET_TIDSLINJE_ARBEIDSSITUASJON = 'SET_TIDSLINJE_ARBEIDSSITUASJON';
export const BRUKER_ER_INNLOGGET = 'BRUKER_ER_INNLOGGET';
export const BRUKER_ER_UTLOGGET = 'BRUKER_ER_UTLOGGET';
export const SJEKKER_INNLOGGING = 'SJEKKER_INNLOGGING';
export const SJEKK_INNLOGGING_FEILET = 'SJEKK_INNLOGGING_FEILET';
export const SJEKK_INNLOGGING_FORESPURT = 'SJEKK_INNLOGGING_FORESPURT';
export const HENT_BRUKERINFO_FORESPURT = 'HENT_BRUKERINFO_FORESPURT';

export const HENT_AKTUELLE_ARBEIDSGIVERE_FEILET = 'HENT_AKTUELLE_ARBEIDSGIVERE_FEILET';
export const HENTER_AKTUELLE_ARBEIDSGIVERE = 'HENTER_AKTUELLE_ARBEIDSGIVERE';
export const SET_AKTUELLE_ARBEIDSGIVERE = 'SET_AKTUELLE_ARBEIDSGIVERE';
export const HENT_AKTUELLE_ARBEIDSGIVERE_FORESPURT = 'HENT_AKTUELLE_ARBEIDSGIVERE_FORESPURT';

export const HENT_ALLE_ARBEIDSGIVERE_FORESPURT = 'HENT_ALLE_ARBEIDSGIVERE_FORESPURT';
export const HENTER_ALLE_ARBEIDSGIVERE = 'HENTER_ALLE_ARBEIDSGIVERE';
export const ALLE_ARBEIDSGIVERE_HENTET = 'ALLE_ARBEIDSGIVERE_HENTET';
export const HENT_ALLE_ARBEIDSGIVERE_FEILET = 'HENT_ALLE_ARBEIDSGIVERE_FEILET';

export const HENTER_DINE_SYKMELDINGER = 'HENTER_DINE_SYKMELDINGER';
export const HENT_DINE_SYKMELDINGER_FEILET = 'HENT_DINE_SYKMELDINGER_FEILET';
export const SET_DINE_SYKMELDINGER = 'SET_DINE_SYKMELDINGER';
export const SET_SORTERING = 'SET_SORTERING';
export const HENT_DINE_SYKMELDINGER_FORESPURT = 'HENT_DINE_SYKMELDINGER_FORESPURT';

export const SET_ARBEIDSSITUASJON = 'SET_ARBEIDSSITUASJON';
export const SET_ARBEIDSGIVER = 'SET_ARBEIDSGIVER';
export const SENDER_SYKMELDING = 'SENDER_SYKMELDING';
export const SEND_SYKMELDING_FEILET = 'SEND_SYKMELDING_FEILET';
export const SYKMELDING_SENDT = 'SYKMELDING_SENDT';
export const BEKREFTER_SYKMELDING = 'BEKREFTER_SYKMELDING';
export const BEKREFT_SYKMELDING_FEILET = 'BEKREFT_SYKMELDING_FEILET';
export const SYKMELDING_BEKREFTET = 'SYKMELDING_BEKREFTET';
export const AVBRYTER_SYKMELDING = 'AVBRYTER_SYKMELDING';
export const AVBRYT_SYKMELDING_FEILET = 'AVBRYT_SYKMELDING_FEILET';
export const SYKMELDING_AVBRUTT = 'SYKMELDING_AVBRUTT';
export const SET_OPPLYSNINGENE_ER_RIKTIGE = 'SET_OPPLYSNINGENE_ER_RIKTIGE';
export const SET_FEILAKTIG_OPPLYSNING = 'SET_FEILAKTIG_OPPLYSNING';
export const BEKREFT_SYKMELDING_FORESPURT = 'BEKREFT_SYKMELDING_FORESPURT';
export const SEND_SYKMELDING_TIL_ARBEIDSGIVER_FORESPURT = 'SEND_SYKMELDING_TIL_ARBEIDSGIVER_FORESPURT';
export const AVBRYT_SYKMELDING_FORESPURT = 'AVBRYT_SYKMELDING_FORESPURT';

export const HENT_LEDERE_FORESPURT = 'HENT_LEDERE_FORESPURT';
export const HENTER_LEDERE = 'HENTER_LEDERE';
export const LEDERE_HENTET = 'LEDERE_HENTET';
export const HENT_LEDERE_FEILET = 'HENT_LEDERE_FEILET';
export const AVKREFT_LEDER_FORESPURT = 'AVKREFT_LEDER_FORESPURT';
export const LEDER_AVKREFTET = 'LEDER_AVKREFTET';
export const LEDER_AVKREFTET_FEILET = 'LEDER_AVKREFTET_FEILET';
export const AVKREFTER_LEDER = 'AVKREFTER_LEDER';

export const HENTER_SYKEPENGESOKNADER = 'HENTER_SYKEPENGESOKNADER';
export const HENT_SYKEPENGESOKNADER_FEILET = 'HENT_SYKEPENGESOKNADER_FEILET';
export const SYKEPENGESOKNADER_HENTET = 'SYKEPENGESOKNADER_HENTET';
export const HENT_SYKEPENGESOKNADER_FORESPURT = 'HENT_SYKEPENGESOKNADER_FORESPURT';
export const SEND_SYKEPENGESOKNAD_FORESPURT = 'SEND_SYKEPENGESOKNAD_FORESPURT';
export const SEND_SYKEPENGESOKNAD_FEILET = 'SEND_SYKEPENGESOKNAD_FEILET';
export const SYKEPENGESOKNAD_SENDT = 'SYKEPENGESOKNAD_SENDT';
export const SENDER_SYKEPENGESOKNAD = 'SENDER_SYKEPENGESOKNAD';

export const HENT_TIDSLINJER_FEILET = 'HENT_TIDSLINJER_FEILET';
export const HENTER_TIDSLINJER = 'HENTER_TIDSLINJER';
export const SET_TIDSLINJER = 'SET_TIDSLINJER';
export const HENT_TIDSLINJER_FORESPURT = 'HENT_TIDSLINJER_FORESPURT';

export const HENT_VEDLIKEHOLD_FEILET = 'HENT_VEDLIKEHOLD_FEILET';
export const HENTER_VEDLIKEHOLD = 'HENTER_VEDLIKEHOLD';
export const VEDLIKEHOLD_HENTET = 'VEDLIKEHOLD_HENTET';
export const HENT_VEDLIKEHOLD_FORESPURT = 'HENT_VEDLIKEHOLD_FORESPURT';

export const HENT_PILOT_SYKEPENGER_FORESPURT = 'HENT_PILOT_SYKEPENGER_FORESPURT';
export const HENTER_PILOT_SYKEPENGER = 'HENTER_PILOT_SYKEPENGER';
export const PILOT_SYKEPENGER_HENTET = 'PILOT_SYKEPENGER_HENTET';
export const HENT_PILOT_SYKEPENGER_FEILET = 'HENT_PILOT_SYKEPENGER_FEILET';

export const SEND_SKJEMA_FEILET = 'SEND_SKJEMA_FEILET';
export const SEND_SKJEMA_FEILET_HANDTERT = 'SEND_SKJEMA_FEILET_HÅNDTERT';
export const SKJEMA_ER_GYLDIG = 'SKJEMA_ER_GYLDIG';

export const HENT_OPPFOLGINGSDIALOGER_FORESPURT = 'HENT_OPPFOLGINGSDIALOGER_FORESPURT';
export const HENTER_OPPFOLGINGSDIALOGER = 'HENTER_OPPFOLGINGSDIALOGER';
export const OPPFOLGINGSDIALOGER_HENTET = 'OPPFOLGINGSDIALOGER_HENTET';
export const HENT_OPPFOLGINGSDIALOGER_FEILET = 'HENT_OPPFOLGINGSDIALOGER_FEILET';
