const milepaelerData = [{
    ledetekst: 'tidslinje.med-arbeidsgiver.snakk.med.arbeidsgiver',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 0,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen4uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.dialogmote-arbeidsgiver',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 1,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen7uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.aktivitetskrav',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 2,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen8uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.dialogmote-nav',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 3,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen26uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.langtidssykmeldt',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 4,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen39uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.sluttfasen',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 5,
    bilde: '/sykefravaer/img/tidslinje/sluttfasen.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.start',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 6,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen8uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.dialog',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 7,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen12uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.aktivitetsplan',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 8,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen39uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.sluttfasen',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    id: 9,
    bilde: '/sykefravaer/img/tidslinje/sluttfasen.svg',
    alt: '',
}];

export default milepaelerData;

