const milepaelerData = [{
    ledetekst: 'tidslinje.med-arbeidsgiver.snakk.med.arbeidsgiver',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'START',
    key: 0,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen4uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.dialogmote-arbeidsgiver',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 1,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen7uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.aktivitetskrav',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 2,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen8uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.dialogmote-nav',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 3,
    bilde: '/sykefravaer/img/tidslinje/med-arbeidsgiver/innen26uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.langtidssykmeldt',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 4,
}, {
    ledetekst: 'tidslinje.med-arbeidsgiver.sluttfasen',
    visning: ['MED_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 5,
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.start',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'START',
    key: 6,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen8uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.dialog',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 7,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen12uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.aktivitetsplan',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 8,
    bilde: '/sykefravaer/img/tidslinje/uten-arbeidsgiver/innen39uker.svg',
    alt: '',
}, {
    ledetekst: 'tidslinje.uten-arbeidsgiver.sluttfasen',
    visning: ['UTEN_ARBEIDSGIVER'],
    type: 'MILEPAEL',
    key: 9,
}];

export default milepaelerData;

