export const PATIENT_OVER_70_YEARS = 'PATIENT_OVER_70_YEARS';
export const UNKNOWN_DIAGNOSECODE_TYPE = 'UNKNOWN_DIAGNOSECODE_TYPE';
export const INVALID_KODEVERK_FOR_BI_DIAGNOSE = 'INVALID_KODEVERK_FOR_BI_DIAGNOSE';
export const INVALID_RULESET_VERSION = 'INVALID_RULESET_VERSION';
export const BEHANDLER_NOT_VALID_IN_HPR = 'BEHANDLER_NOT_VALID_IN_HPR';
export const BEHANDLER_NOT_VALID_AUTHORIZATION_IN_HPR = 'BEHANDLER_NOT_VALID_AUTHORIZATION_IN_HPR';
export const BEHANDLER_NOT_LE_KI_MT_TL_IN_HPR = 'BEHANDLER_NOT_LE_KI_MT_TL_IN_HPR';
export const BEHANDLER_SUSPENDED = 'BEHANDLER_SUSPENDED';
